release:
  github:
    owner: andig
    name: evcc
# before:
#   hooks:
#   - make npm assets
builds:
- id: evcc
  main: main.go
  flags:
  - -tags=release
  ldflags:
  - -X github.com/andig/evcc/server.Version={{.Version}} -X github.com/andig/evcc/server.Commit={{.ShortCommit}}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - "6"
archives:
- builds:
  - evcc
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - evcc.dist.yaml
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^chore'
    - '^bump'
    - '^docs:'
    - '^test:'
